--DROP TABLE IF EXISTS attachment;  
--CREATE TABLE attachment (  
--id INT AUTO_INCREMENT  PRIMARY KEY,  
--actual_file_name VARCHAR(1024) NOT NULL,
--actual_path_file_name VARCHAR(1024) NOT NULL, 
--random_file_name VARCHAR(128) NOT NULL,  
--file_type VARCHAR(1024) NOT NULL  
--); 
